<a href="https://colab.research.google.com/github/pritrakholiya2512-pixel/PRIT_TASKS/blob/main/PRIT_D-2_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[10, 20, 30],[40, 50, 60]])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

# Indexing
print("\nFirst Element:", arr1[0,0])
print("Last Element:", arr1[1,2])

# Mathematical Operations
print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr2 - arr1)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDivision:")
print(arr2 / arr1)

# 15 NumPy Methods

print("\nShape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)

print("\nSum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))
print("Standard Deviation:", np.std(arr1))

print("\nTranspose:")
print(np.transpose(arr1))

print("\nFlatten:")
print(arr1.flatten())

print("\nSorted Array:")
print(np.sort(arr2))

print("\nSquare Root:")
print(np.sqrt(arr2))

print("\nPower:")
print(np.power(arr1, 2))

print("\nReshape:")
print(arr1.reshape(3,2))

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

First Element: 1
Last Element: 6

Addition:
[[11 22 33]
 [44 55 66]]

Subtraction:
[[ 9 18 27]
 [36 45 54]]

Multiplication:
[[ 10  40  90]
 [160 250 360]]

Division:
[[10. 10. 10.]
 [10. 10. 10.]]

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933

Transpose:
[[1 4]
 [2 5]
 [3 6]]

Flatten:
[1 2 3 4 5 6]

Sorted Array:
[[10 20 30]
 [40 50 60]]

Square Root:
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]

Power:
[[ 1  4  9]
 [16 25 36]]

Reshape:
[[1 2]
 [3 4]
 [5 6]]
